"""baseline schema

Revision ID: 7a87ebb77c54
Revises: 
Create Date: 2026-09-06 01:28:33.256565
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '7a87ebb77c54'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('cve_id', sa.String(length=20), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.Column('acknowledged', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_cve_id'), 'alerts', ['cve_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('user_name', sa.String(length=100), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cves',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cve_id', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('published_date', sa.DateTime(), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.Column('cwes', sa.JSON(), nullable=True),
    sa.Column('products', sa.JSON(), nullable=True),
    sa.Column('references', sa.JSON(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('priority', sa.String(length=5), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cves_cve_id'), 'cves', ['cve_id'], unique=True)
    op.create_table('cvss_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cve_id', sa.String(length=20), nullable=False),
    sa.Column('version', sa.String(length=10), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('vector_string', sa.String(length=300), nullable=True),
    sa.Column('attack_vector', sa.String(length=20), nullable=True),
    sa.Column('attack_complexity', sa.String(length=20), nullable=True),
    sa.Column('privileges_required', sa.String(length=20), nullable=True),
    sa.Column('user_interaction', sa.String(length=20), nullable=True),
    sa.Column('scope', sa.String(length=20), nullable=True),
    sa.Column('confidentiality', sa.String(length=20), nullable=True),
    sa.Column('integrity', sa.String(length=20), nullable=True),
    sa.Column('availability', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cvss_scores_cve_id'), 'cvss_scores', ['cve_id'], unique=False)
    op.create_table('epss_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cve_id', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('previous_score', sa.Float(), nullable=True),
    sa.Column('percentile', sa.Float(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_epss_scores_cve_id'), 'epss_scores', ['cve_id'], unique=True)
    op.create_table('exploit_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cve_id', sa.String(length=20), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('stars', sa.Integer(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exploit_sources_cve_id'), 'exploit_sources', ['cve_id'], unique=False)
    op.create_table('kev_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cve_id', sa.String(length=20), nullable=False),
    sa.Column('vendor', sa.String(length=100), nullable=True),
    sa.Column('product', sa.String(length=200), nullable=True),
    sa.Column('vulnerability_name', sa.String(length=500), nullable=True),
    sa.Column('date_added', sa.String(length=30), nullable=True),
    sa.Column('short_description', sa.Text(), nullable=True),
    sa.Column('required_action', sa.String(length=500), nullable=True),
    sa.Column('due_date', sa.String(length=30), nullable=True),
    sa.Column('known_ransomware_campaign_use', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kev_entries_cve_id'), 'kev_entries', ['cve_id'], unique=True)
    op.create_table('remediation_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cve_id', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('assigned_to', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('history', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_remediation_records_cve_id'), 'remediation_records', ['cve_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_remediation_records_cve_id'), table_name='remediation_records')
    op.drop_table('remediation_records')
    op.drop_index(op.f('ix_kev_entries_cve_id'), table_name='kev_entries')
    op.drop_table('kev_entries')
    op.drop_index(op.f('ix_exploit_sources_cve_id'), table_name='exploit_sources')
    op.drop_table('exploit_sources')
    op.drop_index(op.f('ix_epss_scores_cve_id'), table_name='epss_scores')
    op.drop_table('epss_scores')
    op.drop_index(op.f('ix_cvss_scores_cve_id'), table_name='cvss_scores')
    op.drop_table('cvss_scores')
    op.drop_index(op.f('ix_cves_cve_id'), table_name='cves')
    op.drop_table('cves')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_alerts_cve_id'), table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
